getaway/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/restaurants/:id/:user_id" => 'restaurants#show'  

  devise_scope :user do
    
    get '/login/:id', to: 'users/sessions#new'
    get '/loggedin/:id' => 'users/sessions#after_login'

    delete '/logout/:id', to: 'users/sessions#destroy'

    resources :restaurants do 

      resources :users

    end

  end

  

  delete '/queues/:id' => 'queues#destroy'

end

getaway/app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :owner, :class_name => "User", :foreign_key => "user_id"
  has_many :visits
  has_many :menu_items

  def self.find_restaurant(id)
    Restaurant.find(id)
  end

  def current_wating_list
    @list = self.visits.where(status: 'waiting')
  end
end

getaway/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def show

    if user_signed_in?
      @current_user = current_user
      @restaurant = Restaurant.find_restaurant(params[:id])
      @waiting_list = @restaurant.current_wating_list      

      # showing the orders from the customer  
      if params[:user_id]
        @visit = Visit.current_waiting(params[:user_id])
        @orders = VisitMenuItem.find_orders(@visit.id)
        @total_price = @orders.inject(0) {|total, menu| total + menu.menu_item.price}
      end    
 
    else
      redirect_to "/login/#{parmas[:id]}"
    end    

    respond_to :html, :js 

  end

end

getaway/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

getaway/app/views/restaurants/_map.html.erb
<div class="restaurant-content-header">
	Map
</div>

getaway/app/views/restaurants/_menu.html.erb
	<div class="restaurant-content-header">
		Menu
	</div>
	<div class="restaurant-menu-logo">
	</div>
	<div class="pure-u-1">
		<div class="add-menu-item">
			<button id="add-item">Add Item</button>
		</div>
	</div>
	<div class="restaurant-menu-content">
		<table id="menu-table">
		  <thead>
		    <tr>
		      <th>Item</th>
		      <th>Price</th>
		      <th>Action</th>
		    </tr>
		  </thead>

		  <tbody>
		  	<% @restaurant.menu_items.each do |menu_item| %>
		  	<tr>
		    <td>#<%=menu_item.name%></td>
		    <td>$<%=menu_item.price%></td>
		    <td class="orders"> <a href="javascript:void(0)"><%= image_tag "edit.png", :class => 'glass', :id =>'glass' %></a><a href="javascript:void(0)"><%= image_tag "delete.png", :class => 'glass', :id =>'glass' %></a> </td>
			</tr>
			<% end %>
		  </tbody>
		</table>
	</div>
</div>

getaway/app/views/restaurants/_order.html.erb
<!-- MODAL CONTENT GUARD -->
<div class="pure-u-1">
  <div id="modal">
    <div class = "pure-u-1">
      <div class = "modal-wrapper">
        <!-- MODAL - CONTENT -->
        <div class="modal-content">
          <!-- CLOSE MODAL -->
           <div class = "pure-u-1">
                <a href="javascript:void(0)"><div class = "modal-close" id="close-modal">
                  X 
                </div></a>
            </div>
          <!-- MODAL - HEADER -->
            <div class="pure-u-1">
              <div class = "modal-logo">
                Order List
              </div>
            </div>

           <div class = "pure-u-1">
            <div class="modal-body">
              <table>
                <thead>
                  <tr>
                    <th>Item</th>
                    <!-- <th>Quantity</th> -->
                    <th>Price</th>
                  </tr>
                </thead>

              <tbody id="order_list">
                <%= render partial: 'order_list', locals: {orders: @orders}%>
              </tbody>
            </table>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

getaway/app/views/restaurants/_order_list.html.erb
<% if orders %>
  
  <% orders.each do |menu| %>

  <tr>
    <td><%=menu.menu_item.name%></td>
    <td>$<%=menu.menu_item.price%></td>
  </tr>
  
  <% end %>
  <tr>
    <% if @total_price > 0 %>
      <td>Total Amount:</td>
      <td> $<%= @total_price%> </td>
    <% else %>
      <td>No orders yet</td>  
      <td></td>
    <% end %>
  </tr>
<% end %>

getaway/app/views/restaurants/_queue.html.erb
<div class="pure-u-1">
	<div class="restaurant-content-header">
		Queue
	</div>
	<div class="next-button">
		<button id="next" name = "next" value = "<%=@waiting_list.first.user.id if @waiting_list.first%> <%=@waiting_list.first.user.name if @waiting_list.first %>"> NEXT </button>
	</div>
</div>
<div class="restaurant-queue-content">
	<table id="queue-table">
	  <thead>
	    <tr>
	      <th>Ticket</th>
	      <th>Name</th>
	      <th>Orders</th>
	    </tr>
	  </thead>

	  <tbody>
	  	<% @waiting_list.each do |customer| %>
		  	<tr>
			    <td>#<%=customer.id%></td>

			    <% if customer.user.name%>
			    	<td><%=customer.user.name%></td>
			    <% else %>	
			    	<td><%=customer.user.email%></td>
			    <% end %>

		   		<td class="orders"> 
						<%= link_to '<button type="button" id="view">View</button>'.html_safe, "/restaurants/#{@restaurant.id}/#{customer.user_id}", :remote => true%>
				</tr>
			<% end %>
	  </tbody>
</table>
</div>

getaway/app/views/restaurants/show.html.erb
<body class="restaurant-page">

	<div id="sidr-right">
	  <!-- Your content -->
	  <ul>
	    <li><%= link_to 'LOGOUT', "/logout/#{@restaurant.id}", method: :delete%></li>
	    <!-- <li><a href="#">EDIT PROFILE</a></li> -->
	  </ul>
	</div>

	<div class ="pure-g">
		<!-- Navigation Bar -->
		<div class = "pure-u-1">
			<div class="nav-bar-container">
				<div class="pure-u-7-24">
					<div class="nav-bar-logo">

					</div>
				</div>
				<div class="pure-u-15-24">
					<a id="right-menu" href="#right-menu">
						<div class="nav-bar-option-mobile">
						</div>
					</a>
				</div>

			</div>
		</div>

		<script>
			$(document).ready(function() {
			    $('#right-menu').sidr({
			      name: 'sidr-right',
			      side: 'right'
			    });
			});
		</script>


		<!-- Restaurant Banner -->

		<div class="pure-u-1">
			<div class="restaurant-banner">
				Welcome, <%= @restaurant.name %>
			</div>
		</div>


		<!-- Restaurant Controller -->
		<div class="pure-u-1">
			<div class="restaurant-menu-bar">
				<div class="pure-u-3-24">
					<div class="restaurant-queue" id="queue">
						<%= link_to 'Queue', restaurant_path(@restaurant), remote: true %>
					</div>
				</div>
				<div class="pure-u-3-24">
					<div class="restaurant-map" id="map">
						<%= link_to 'Map', restaurant_path(@restaurant), remote: true %>
					</div>
				</div>
				<div class="pure-u-3-24">
					<div class="restaurant-menu" id="menu">
						<%= link_to 'Menu', restaurant_path(@restaurant), remote: true %>
					</div>
				</div>
			</div>
		</div>
		<!-- order partial with modal -->
		<%= render partial: 'order'%>
		<!-- Restaurant -->
		<div class="pure-u-1" >
			<div class="controller-content" id="content">	
				<%= render 'queue' %>
			</div>
		</div>

	</div>
</body>

getaway/app/views/restaurants/show.js.erb
$(document).ready(function() {
  
	$("#queue").off().on('click',function(event){

		$('#content').empty().append("<%= j (render 'queue') %>");
		$("#queue a").css("color","#58759d")
		$(".restaurant-queue").css('border-bottom', 'solid 2px #58759d');
		$("#map a").css("color","#C0C0C0");
		$(".restaurant-map").css('border-bottom', 'solid 2px #C0C0C0');
		$("#menu a").css("color","#C0C0C0");
		$(".restaurant-menu").css('border-bottom', 'solid 2px #C0C0C0');

	})


	$('#map').off().on('click',function(event){
		
		$('#content').empty().append("<%= j (render 'map') %>")
		$("#map a").css("color","#58759d");
		$(".restaurant-map").css('border-bottom', 'solid 2px #58759d');
		$("#queue a").css("color","#C0C0C0");
		$(".restaurant-queue").css('border-bottom', 'solid 2px #C0C0C0');
		$("#menu a").css("color","#C0C0C0");
		$(".restaurant-menu").css('border-bottom', 'solid 2px #C0C0C0');

	})


	$('#menu').off().on('click',function(event){
		
		$('#content').empty().append("<%= j (render 'menu') %>")
		$("#menu a").css("color","#58759d");
		$(".restaurant-menu").css('border-bottom', 'solid 2px #58759d');
		$("#map a").css("color","#C0C0C0");
		$(".restaurant-map").css('border-bottom', 'solid 2px #C0C0C0');
		$("#queue a").css("color","#C0C0C0");
		$(".restaurant-queue").css('border-bottom', 'solid 2px #C0C0C0');
		
	})

	// AJAX for retrieving @order data
	$("#order_list").html("<%= escape_javascript(render partial: 'order_list', locals: { orders: @orders } ) %>"); 

	})